namespace IMS.PRODUCTAPI.Models;

    // DTO = Data Transfer Object
    // Only include what the USER needs to input
    // ProductId is auto generated by database so dont include it
    // Transactions is not needed when creating a product
public class ProductDto
{
        public required string Name { get; set; }
        public string? Description { get; set; }  // still nullable like original
        public required decimal Price { get; set; }
        public required int Stock { get; set; }
}